# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rInhibition <- function(n, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_rInhibition', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rInhibition_internal <- function(n, par, I, x0, maxiter, nonlinear, random) {
    .Call('_pedxing_rInhibition_internal', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random)
}

#' @export
dInhibition <- function(RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_dInhibition', PACKAGE = 'pedxing', RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rlca <- function(n, kappa, beta, Z, t0, I, x0, dtovertau, tau, maxiter, nonLinear, random) {
    .Call('_pedxing_rlca', PACKAGE = 'pedxing', n, kappa, beta, Z, t0, I, x0, dtovertau, tau, maxiter, nonLinear, random)
}

#' @export
rLeak <- function(n, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_rLeak', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rLeak_internal <- function(n, par, I, x0, maxiter, nonlinear, random) {
    .Call('_pedxing_rLeak_internal', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random)
}

#' @export
dLeak <- function(RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_dLeak', PACKAGE = 'pedxing', RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rInput <- function(n, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_rInput', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rInput_internal <- function(n, par, I, x0, maxiter, nonlinear, random) {
    .Call('_pedxing_rInput_internal', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random)
}

#' @export
dInput <- function(RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_dInput', PACKAGE = 'pedxing', RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rvB <- function(n, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_rvB', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random, debug)
}

#' @export
rvB_internal <- function(n, par, I, x0, maxiter, nonlinear, random) {
    .Call('_pedxing_rvB_internal', PACKAGE = 'pedxing', n, par, I, x0, maxiter, nonlinear, random)
}

#' @export
dvB <- function(RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug) {
    .Call('_pedxing_dvB', PACKAGE = 'pedxing', RT, R, nsim, par, I, x0, maxiter, nonlinear, random, debug)
}

